package illa4257.i4Utils.ir;

public enum Opcode {
    STORE,
    GET_STATIC,

    // Math
    ADD, SUBTRACT, MULTIPLY, DIVIDE,

    // Conditional
    AND, OR, XOR,
    IF_LE,
    GOTO,

    // Control
    ARRAY_LENGTH,
    INVOKE_VIRTUAL,
    INVOKE_SPECIAL,
    INVOKE_STATIC,
    ALLOCATE,
    RETURN,
    ARRAY_GET, IF_GE, PUT_STATIC, GET_FIELD, IF_NULL, PUT_FIELD, CHECK_CAST, IF_EQ, NO_OP, INSTANCEOF, MONITOR_ENTER, MONITOR_EXIT, IF_NONNULL, ANCHOR, NEW_ARRAY, CATCH, TRY, IF_NE, COMPARE, IF_LT, THROW
}