package illa4257.i4Utils.ir;

public enum Opcode {
    STORE,
    GET_STATIC,
    PUT_STATIC,
    GET_FIELD, PUT_FIELD,
    ARRAY_GET,

    // Math
    ADD, SUBTRACT, MULTIPLY, DIVIDE, REMAINDER,

    // Conditional
    AND, OR, XOR,
    IF_NULL, IF_NONNULL, IF_EQ, IF_NE,
    IF_LT, IF_LE,
    IF_GT, IF_GE,
    GOTO,

    // Control
    ANCHOR,
    ARRAY_LENGTH,
    INVOKE_VIRTUAL,
    INVOKE_SPECIAL,
    INVOKE_STATIC,
    ALLOCATE,
    NEW_ARRAY,
    RETURN,
    THROW,
    TRY,
    CATCH,
    MONITOR_ENTER,
    MONITOR_EXIT,

    CHECK_CAST,
    NO_OP,
    INSTANCEOF,
    ARRAY_SET, INVOKE_INTERFACE, SHIFT_RIGHT, INT2LONG, LONG2INT, SHIFT_LEFT, DOUBLE2FLOAT, DOUBLE2INT, DOUBLE2LONG, COMPARE_NAN, NEGATIVE, FLOAT2DOUBLE, FLOAT2INT, FLOAT2LONG, INT2BYTE, INT2CHAR, INT2DOUBLE, INT2FLOAT, INT2SHORT, INVOKE_DYNAMIC, LONG2DOUBLE, LONG2FLOAT, UNSIGNED_SHIFT_RIGHT, COMPARE
}